export default{
    products: [
        {
            _id:'1',
            name: 'full zip tshirt',
            category: 'shirts',
            image:'images/product1.jpeg',
            price: 60,
            brand: 'nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'2',
            name: 'Gonnetta ',
            category: 'gonna',
            image:'images/product-2.jpg',
            price: 60,
            brand: 'nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'3',
            name: 'pants ',
            category: 'pantaloni',
            image: 'images/product-3.jpg',
            price: 60,
            brand: 'nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'4',
            name: 'altro ',
            category: 'altro',
            image: 'images/product-4.jpg',
            price: 60,
            brand: 'nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'5',
            name: 'full smok ',
            category: 'smoking',
            image: 'images/product-5.jpg',
            price: 60,
            brand: 'nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'6',
            name: 'other ',
            category: 'other',
            image: 'images/product-6.jpg',
            price: 60,
            brand: 'nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'7',
            name: 'full zip tshirt',
            category: 'shirts',
            image:'images/product1.jpeg',
            price: 69,
            brand: 'nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
    ],
};