export default{
    products: [
        {
            _id:'1',
            name: 'T-shirt Nike',
            category: 'shirts',
            image:'images/product1.png',
            price: 30.99,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'2',
            name: 'Gonna Monroe',
            category: 'gonna',
            image:'images/product-2.png',
            price: 59.99,
            brand: 'Gucci',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'3',
            name: 'Piumino',
            category: 'pantaloni',
            image: 'images/product-3.png',
            price: 109.99,
            brand: 'Colmar',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'4',
            name: 'Jeans',
            category: 'altro',
            image: 'images/product-4.jpg',
            price: 45.99,
            brand: 'Armani',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'5',
            name: 'Smoking',
            category: 'smoking',
            image: 'images/product-5.png',
            price: 130.99,
            brand: 'Sartoriale',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'6',
            name: 'Jeans',
            category: 'other',
            image: 'images/product-6.png',
            price: 79.99,
            brand: 'Diesel',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'7',
            name: 'T-Shirt',
            category: 'shirts',
            image:'images/product-7.jpg',
            price: 69.99,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'8',
            name: 'Abito',
            category: 'shirts',
            image:'images/product-8.jpg',
            price: 159.99,
            brand: 'Versace',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'9',
            name: 'Abito',
            category: 'gonna',
            image:'images/product-9.jpg',
            price: 169.99,
            brand: 'D&G',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'10',
            name: 'Jeans',
            category: 'pantaloni',
            image: 'images/product-10.jpg',
            price: 69.99,
            brand: 'Diesel',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'11',
            name: 'T-Shirt',
            category: 'altro',
            image: 'images/product-11.jpg',
            price: 64.99,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'12',
            name: 'Body',
            category: 'smoking',
            image: 'images/product-12.jpg',
            price: 64.99,
            brand: 'Tezenis',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'13',
            name: 'T-Shirt',
            category: 'other',
            image: 'images/product-13.jpg',
            price: 79.99,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },{
            _id:'14',
            name: 'T-Shirt',
            category: 'shirts',
            image:'images/product-14.jpg',
            price: 24.99,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'15',
            name: 'T-Shirt',
            category: 'gonna',
            image:'images/product-15.jpg',
            price: 34.99,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'16',
            name: 'T-Shirt',
            category: 'pantaloni',
            image: 'images/product-16.jpg',
            price: 44.99,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
       
    ],
};